### ISSUE TITLE
[Bug]: Crash when selecting bounty on modded server

### ISSUE THREAD

**Issue by ewickly** [ejektaflex/Bountiful#243] opened 2023-07-24 02:08 UTC
### What happened?

When selecting bounty, it crashes the client. Has happened to client as well as others who are connected to singleplayer world via Essential mod

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Relevant log output

[debug-1.log](https://github.com/ejektaflex/Bountiful/files/12141081/debug-1.log)

**Comment by ejektaflex** [comment] 2023-07-24 02:12
Closing as duplicate of #242, thanks for the extra log, it's very helpful!

**Closed as completed by ejektaflex** 2023-07-24 02:12 UTC
Labels: bug
