### ISSUE TITLE
[Bug]: Invalid pool item

### ISSUE THREAD

**Issue by Congraz8961** [ejektaflex/Bountiful#161] opened 2021-12-22 20:36 UTC
### What happened?

I have just discovered on the console that mistakes are coming up around the mod. I experience some lag spikes once in a while when I perform a bounty.

### How can we reproduce it?

I have no idea, I can show you my forge version and the error that appears.

Forge version: 1.16.5-36.2.20
Bountiful version: 1.16.4-3.3.1

### Mod Version

Bountiful version: 1.16.4-3.3.1

### Forge Version

Forge version: 1.16.5-36.2.20

### Relevant log output

![image](https://user-images.githubusercontent.com/56209437/147152047-fd5ec14c-467c-4cd4-a848-52814645d677.png)
![image](https://user-images.githubusercontent.com/56209437/147152118-284ca428-ff7a-443c-9e89-38b8b8976a8c.png)

**Comment by ejektaflex** [comment] 2021-12-22 21:00
This is not a bug - the warnings just warn you of entries that do not exist in your current game. They will not get loaded into Bountiful, so they won't affect your gameplay. 

The two item tag bounties will not load because [they are not implemented in 1.16](https://github.com/ejektaflex/Bountiful/blob/develop/CHANGELOG.md#removals).

The loot table error is a duplicate of #157 / #126 / #122 / #99 .

No actual bugs or problems here, so this will be closed.

**Closed as completed by ejektaflex** 2021-12-22 21:00 UTC
Labels: cosmetic
