### ISSUE TITLE
Server Crash with Bountiful 1.15.2

### ISSUE THREAD

**Issue by kwhite59** [ejektaflex/Bountiful#98] opened 2020-08-13 20:24 UTC
## Bug Report

**Observed Behaviour**

What happened: When starting up my server for the first time, it crashes.

Crash log: 
---- Minecraft Crash Report -------- Minecraft Crash Report ----// I bet Cylons wouldn't have this problem.
Time: 8/11/20, 6:28 AMDescription: Exception in server tick loop
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ Bountiful (bountiful) encountered an error during the common_setup event phase§7java.lang.IllegalAccessException: Can not set static final net.minecraft.world.gen.feature.jigsaw.JigsawPatternRegistry field net.minecraft.world.gen.feature.jigsaw.JigsawManager.field_214891_a to ejektaflex.bountiful.worldgen.JigsawJank$OperatorRegistry] at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading} at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:156) ~[?:?] {re:classloading} at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading} at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:835) [?:?] {}
 
A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.15.2 Minecraft Version ID: 1.15.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 12.0.2, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation Memory: 899962112 bytes (858 MB) / 1711276032 bytes (1632 MB) up to 8573157376 bytes (8176 MB) CPUs: 12 JVM Flags: 0 total;  ModLauncher: 5.1.2+70+master.2845bb9 ModLauncher launch target: fmlserver ModLauncher naming: srg ModLauncher services:  /eventbus-2.2.0-service.jar eventbus PLUGINSERVICE  /forge-1.15.2-31.2.36.jar object_holder_definalize PLUGINSERVICE  /forge-1.15.2-31.2.36.jar runtime_enum_extender PLUGINSERVICE  /forge-1.15.2-31.2.36.jar capability_inject_definalize PLUGINSERVICE  /accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE  /forge-1.15.2-31.2.36.jar runtimedistcleaner PLUGINSERVICE  /forge-1.15.2-31.2.36.jar fml TRANSFORMATIONSERVICE  FML: 31.2 Forge: net.minecraftforge:31.2.36 FML Language Providers:  javafml@31.2 minecraft@1 kotlinforforge@1.3.1 kotlinfml@1.5.2 Mod List:  forge-1.15.2-31.2.36-server.jar Minecraft {minecraft@1.15.2 SIDED_SETUP} forge-1.15.2-31.2.36-universal.jar Forge {forge@31.2.36 SIDED_SETUP} Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 ERROR} Data Packs:  Is Modded: Definitely; Server brand changed to 'forge' Type: Dedicated Server (map_server.txt)

**Minimal setup needed to reproduce**

- Forge version: Tested on 1.15.2 - 31.2.36 and 1.15.2 - 31.2.0
- Bountiful version:  1.15.2
- Other mods: None

- This does not happen in single player, atleast I havent experienced it yet.

**Comment by ejektaflex** [comment] 2020-08-13 22:46
Thanks for the crash report. It might be an issue with Forge mappings being out of date, but I don't quite see why that should cause a problem. Forge may have done something on their end that caused a problem. I'll look into it when I have some time.

**Comment by ejektaflex** [comment] 2021-03-14 20:54
I've been unable to reproduce this in 1.15 - though all maintenance is now only for 1.16, so I'm closing this issue. Stay healthy!

**Closed as completed by ejektaflex** 2021-03-14 20:54 UTC
Labels: bug

**Comment by gimunyang** [comment] 2021-10-01 03:12
I know this is closed but I ran into the same error recently - it seems to do with the Java Runtime version, assuming the call `org.apache.commons.lang3.reflect.FieldUtils.removeFinalModifier()` isn't working as intended? But it has something to do with that...

Anyway, downgrading the runtime to JVM 1.8 (`1.8.0_291`) works fine, whereas `14.0.1` showed the same error.
