### ISSUE TITLE
Entity name showing weird on custom bounty

### ISSUE THREAD

**Issue by AdaraChristine** [ejektaflex/Bountiful#25] opened 2019-01-18 06:34 UTC
![2019-01-17_22 32 43](https://user-images.githubusercontent.com/30163566/51369311-e8da6c00-1aa7-11e9-9f24-9d45700e02d0.png)

/bo entities =  junglemobs:conba

my entry in the config= "content": "entity:junglemobs:conba",

**Comment by ejektaflex** [comment] 2019-01-18 08:16
Thanks, I'll look into this. I tested it on three mods that each registered names differently, but this must be an outlier.

**Comment by ejektaflex** [comment] 2019-01-31 11:38
I'm going to close this because the issue is part of Lycanite's Mobs, so look at the linked issue in the previous comment for further updates.

The problem was that there are two places where you should be giving an Entity it's translation key, and in Lycanite's **this key is _not_ the same in both places**. Because of that, it's trying to translate the mismatched translation key which doesn't have a valid translation.

**Closed by ejektaflex** 2019-01-31 11:38 UTC
Labels: other mod
