### ISSUE TITLE
I can't move or select the Bounty Table on my inventory

### ISSUE THREAD

**Issue by KuroxP** [ejektaflex/Bountiful#77] opened 2020-05-04 21:49 UTC
## Bug Report

**Observed Behaviour**

What happened: Ok so my problem is that when I pass around my cursor on an item, for example, "Obsidian" on the cursor appears "Obsidian" but, when I try to pass my cursor on the Bounty Board in my inventory, the game just stop and Minecraft is closed

Crash log: 
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/05/20 5:40
Description: Rendering screen

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method ejektaflex.bountiful.block.BlockBountyBoard.func_176195_g, parameter worldIn
	at ejektaflex.bountiful.block.BlockBountyBoard.func_176195_g(BlockBountyBoard.kt) ~[?:1.15.2-3.1.0] {re:classloading}
	at harmonised.pmmo.events.ClientEventHandler.tooltipEvent(ClientEventHandler.java:174) ~[?:2.22.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_135_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:266) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:678) ~[?:?] {re:classloading,xf:optiforge:default,re:mixin}
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.renderTooltip(CreativeScreen.java:688) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.render(CreativeScreen.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:367) ~[?:?] {re:mixin,re:classloading}
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:746) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:800) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.44.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$476/249696914.call(Unknown Source) [forge-1.15.2-31.1.44.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ejektaflex.bountiful.block.BlockBountyBoard.func_176195_g(BlockBountyBoard.kt)
	at harmonised.pmmo.events.ClientEventHandler.tooltipEvent(ClientEventHandler.java:174)
	at net.minecraftforge.eventbus.ASMEventHandler_135_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:266)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:678)
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:121)
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116)
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.renderTooltip(CreativeScreen.java:688)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149)
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.render(CreativeScreen.java:637)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:367)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:746)

**Expected Behaviour**

What should have happened:

**Minimal setup needed to reproduce**

- Forge version: 31.1.44
- Bountiful version: 3.1.0
- Other mods:
Mod List: 
		-followingvillagers-1.15.2-1.4.0.jar Following Villagers {followingvillagers@1.15.2-1.4.0 DONE}
		-NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		-chanceglobe-1.15.2-v1.3.4.jar Chance Globe {chanceglobe@v1.3.4 DONE}
		-jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 DONE}
		-OptiForge-MC1.15.2-0.1.12.jar OptiForge {optiforge@0.1.12 DONE}
		-goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		-caelus-FORGE-1.15.2-2.0-beta2.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta2 DONE}
		-Neat+1.6-20.jar Neat {neat@1.6-20 DONE}
		-CoffeeSpawner-1.15.1-6.0.0.jar Coffee Spawner {coffeespawner@1.15.1-6.0.0 DONE}
		-Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		-journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		-Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		-branders-enhanced-mob-spawners-v1.15.2-1.5.4.jar Enhanced Mob Spawners {spawnermod@1.4.4 DONE}
		-The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 DONE}
		-u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		-Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 DONE}
		-dragondropsel_1.15.2-1.0.jar Dragon Drops Elytra {dragondropsel@1.0 DONE}
		-Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		-trash-1.15.2-0.1.4.jar Trash {trash@1.15.2-0.1.4 DONE}
		-PackingTape-1.15.2-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		-endercompass-2.0.jar Ender Compass {endercompass@2.0 DONE}
		-forge-1.15.2-31.1.44-universal.jar Forge {forge@31.1.44 DONE}
		-respawnablepets-1.1.jar Respawnable Pets {respawnablepets@1.1 DONE}
		-ConfigurableCane-1.15.2-1.5.1.jar Configurable Cane {configurablecane@NONE DONE}
		-anviltweaks-2.2a.jar Anvil Tweaks {anviltweaks@2.2a DONE}
		-forge-1.15.2-31.1.44-client.jar Minecraft {minecraft@1.15.2 DONE}
		-mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		-useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		-theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		-BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		-baubles-1.7.1-1.15.2.jar Baubles {baubles@1.7.1 DONE}
		-ferroustry-2.2.jar Ferroustry {ferroustry@2.2 DONE}
		-astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		-Bountiful-1.15.2-3.1.0.jar Bountiful {bountiful@1.15.2-3.1.0 DONE}
		-curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 DONE}
		-Patchouli-1.15.2-1.2-31.jar Patchouli {patchouli@1.15.2-1.2-30 DONE}
		-AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		-[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 DONE}
		-OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		-themidnight-0.5.7-3.jar The Midnight {midnight@0.5.7-3 DONE}
		-lostcities-1.15-3.0.1-alpha.jar LostCities {lostcities@1.15-3.0.1-alpha DONE}
		-libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		-BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		-tombstone-4.3.4-1.15.2.jar Corail Tombstone {tombstone@4.3.4 DONE}
		-Quark-r2.1-231.jar Quark {quark@r2.1-231 DONE}
		-Project+MMO-1.15-2.22.3.jar Project MMO {pmmo@2.22.3 DONE}
		-furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		-curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		-CosmeticArmorReworked-1.15.2-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v1a DONE}
		-parachutemod-1.15.2-3.0.2-479.jar Parachute Mod NG {parachutemod@1.15.2-3.0.2-479 DONE}
		-farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 DONE}

**Steps to reproduce**

How to recreate this:

**Comment by ejektaflex** [comment] 2020-05-05 12:10
Excellent, it looks like this is a duplicate of #79 . I'm closing this issue because they are the same, you can keep track of updates there!

**Closed as completed by ejektaflex** 2020-05-05 12:10 UTC
