### ISSUE TITLE
[Bug]: Bounty Board's Not spawning in some villages

### ISSUE THREAD

**Issue by CrimsonCrips** [ejektaflex/Bountiful#172] opened 2022-03-06 08:16 UTC
### What happened?

I've been in a lot of villages and not once do i see any bounty boards locations
so i tried going in a different world and also maxing the chance of it spawning and going to a bunch of villages and out of all of them plain villages seems to only have the bounty boards

(Note i do have some mods that add new generation in villages)

### Mod Version

1.16

### Forge Version

1.16.5

**Comment by ejektaflex** [comment] 2022-03-08 03:44
I need a log in order to diagnose these types of problems, which is why I ask for one! :^) If you could provide a log, then I can look into it, thanks!

This mod does add bounty boards to villages, so clearly something is wrong. It works for *me*, so I need to know what settings and mods *you* are using that are causing it not to work in order to even start to figure out what's up :)

**Comment by CrimsonCrips** [comment] 2022-03-10 16:12
How do i give a log?

and also here are the mod list 
![image](https://user-images.githubusercontent.com/84312428/157706122-1051579f-9d59-4847-9f7a-0e2e62b5ab64.png)

**Comment by afloofflam** [comment] 2022-03-17 17:20
I'm having a similar issue, however I have _no_ boards showing up in any of my villages. I've attached my latest log file. 

Thank you!

[latest.log](https://github.com/ejektaflex/Bountiful/files/8288438/latest.log)

Edit: I should have mentioned I'm playing ver 1.16.5.

**Comment by pritam20ps05** [comment] 2022-07-17 15:17
I know this Problem if there are no error logs then you can change the rarity of the structure from the config. You are just unlucky to find it.

**Comment by ejektaflex** [comment] 2023-03-30 06:06
Unfortunately, mods that tweak how villages generate will break Bountiful. That's because Bountiful is treated the same way as a house in a village. Mods that override how villages generate will override how Bountiful generates. In the near future, I would like to release modified jigsaw pieces for popular mods that change how villages generate.

**Comment by ejektaflex** [comment] 2023-07-05 22:35
Closing, as I can't reproduce this. It was probably another mod interfering with generation.

**Closed as completed by ejektaflex** 2023-07-05 22:35 UTC
Labels: bug
