### ISSUE TITLE
[1.16.5] Mildly concerning | Server startup eyesore

### ISSUE THREAD

**Issue by Cixon** [ejektaflex/Bountiful#122] opened 2021-03-06 22:13 UTC
## Bug Report
**Context:** Pairing this mod with a variety of other mods in my personal modpack but I couldn't help but to notice this every time I start up my server.

I use forge [1.16.5] 36.0.42, latest Kotlin and Bountiful.
Even though this error doesn't cause crashes, it clogs up the log every time
which is problematic because it just makes troubleshooting real problems harder.

**Start Up Log:** 

[22:06:55] [Worker-Main-2/ERROR] [minecraft/LootTableManager]: Couldn't parse loot table bountiful:blocks/bountyboard
com.google.gson.JsonSyntaxException: Missing ops, expected to find a JsonArray
at net.minecraft.util.JSONUtils.func_151214_t(SourceFile:425) ~[?:?] {re:classloading}
at net.minecraft.loot.functions.CopyNbt$Serializer.func_186530_b(SourceFile:245) ~[?:?] {re:classloading}
at net.minecraft.loot.functions.CopyNbt$Serializer.func_186530_b(SourceFile:231) ~[?:?] {re:classloading}
at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:99) ~[?:?] {re:classloading}
at net.minecraft.loot.LootFunction$Serializer.func_230423_a_(SourceFile:88) ~[?:?] {re:classloading}
at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?] {re:classloading}
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
**+50 lines of red errors.**

**Comment by ejektaflex** [comment] 2021-03-06 22:50
Pretty sure it wants a JsonArray of which ops to supply when copying data from a BlockEntity (the bounty board) into it's item form (the bounty board you hold in your hand), when the block is broken.

And uhh, as far as I'm aware there really aren't any ops that I need to supply, I gave it what was needed. I'll see if I can include any dummy data that would quiet down the console log, but this isn't anything to be concerned about. 

I'm currently trying to fix the same thing for the Fabric version - so whatever changes I make there will be applied here as well.

You can safely ignore it. :^)

**Comment by Cixon** [comment] 2021-03-06 23:20
Thank you kindly!

**Comment by ejektaflex** [comment] 2021-03-14 21:14
I'm going to close this is a duplicate of #99, but leave that open until it is finished. Thanks!

**Closed as completed by ejektaflex** 2021-03-14 21:14 UTC
Labels: cosmetic
