### ISSUE TITLE
[Bug]: TPS Hanging and crashing 

### ISSUE THREAD

**Issue by Zelioth** [ejektaflex/Bountiful#236] opened 2023-07-02 22:08 UTC
### What happened?

While playing in a in a world if you have a TPS monitor it will report that the board is causing hanging and TPS lag. Sometimes the TPS lag/issue will just freeze and crash the client. 

### How can we reproduce it?

It's hit or miss. the TPS issue seems to happen every world but the cashing can be iffy but still annoying 

### Mod Version

6.0.1

### Mod Loader

Forge

### Mod Loader Version

47.0.35

### Relevant log output

net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:663) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: #minecraft:wool
	at net.minecraft.resources.ResourceLocation.m_245413_(ResourceLocation.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at io.ejekta.bountiful.bounty.types.builtin.BountyTypeItem.isValid(BountyTypeItem.java:27) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.data.PoolEntry.isValid(PoolEntry.java:44) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor$lambda$5(BountyCreator.java:207) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor(BountyCreator.java:212) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator$Companion.access$getRewardsFor(BountyCreator.java:186) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator.genRewardEntries(BountyCreator.java:81) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator.create(BountyCreator.java:43) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator.stack_delegate$lambda$1(BountyCreator.java:32) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlinforforge-4.3.0-all.jar%23438!/:?]
	at io.ejekta.bountiful.content.BountyCreator.getStack(BountyCreator.java:31) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.BountyCreator$Companion.createBountyItem(BountyCreator.java:194) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.board.BoardBlockEntity.randomlyUpdateBoard(BoardBlockEntity.java:157) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.board.BoardBlockEntity.tryInitialPopulation(BoardBlockEntity.java:138) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.board.BoardBlockEntity$Companion.tick(BoardBlockEntity.java:277) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.tick(BoardBlock.java:44) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.m_155252_(BoardBlock.java:44) ~[Bountiful-6.0.1+1.20.1-forge.jar%23479!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:895) ~[client-1.20.1-20230612.114412-srg.jar%23718!/:?]
	... 5 more
[latest.log](https://github.com/ejektaflex/Bountiful/files/11931582/latest.log)

**Comment by ejektaflex** [comment] 2023-07-02 23:26
Closing as duplicate of #234

**Closed as completed by ejektaflex** 2023-07-02 23:26 UTC
Labels: bug
