### ISSUE TITLE
[Bug]: Game crashes due to Non [a-z0-9_.-] character in namespace of location: #minecraft:wool

### ISSUE THREAD

**Issue by TheynT** [ejektaflex/Bountiful#235] opened 2023-06-29 16:11 UTC
### What happened?

Game crashes when generating new chunks with Bountiful Boards who refer to #minecraft:wool.

### Mod Version

6.0.1+1.20.1 Fabric

### Mod Loader

Quilt

### Mod Loader Version

0.19.1 / 7.0.4+0.84.0-1.20.1 

### Relevant log output

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-06-29 17:27:19
Description: Ticking block entity

net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: #minecraft:wool
	at net.minecraft.class_2960.method_45135(class_2960.java:232)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.minecraft.class_2960.<init>(class_2960.java:56)
	at io.ejekta.bountiful.bounty.types.builtin.BountyTypeItem.isValid(BountyTypeItem.java:27)
	at io.ejekta.bountiful.data.PoolEntry.isValid(PoolEntry.java:44)
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor$lambda$5(BountyCreator.java:207)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor(BountyCreator.java:212)
	at io.ejekta.bountiful.content.BountyCreator$Companion.access$getRewardsFor(BountyCreator.java:186)
	at io.ejekta.bountiful.content.BountyCreator.genRewardEntries(BountyCreator.java:81)
	at io.ejekta.bountiful.content.BountyCreator.create(BountyCreator.java:43)
	at io.ejekta.bountiful.content.BountyCreator.stack_delegate$lambda$1(BountyCreator.java:32)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ejekta.bountiful.content.BountyCreator.getStack(BountyCreator.java:31)
	at io.ejekta.bountiful.content.BountyCreator$Companion.createBountyItem(BountyCreator.java:194)
	at io.ejekta.bountiful.content.board.BoardBlockEntity.randomlyUpdateBoard(BoardBlockEntity.java:157)
	at io.ejekta.bountiful.content.board.BoardBlockEntity.tryInitialPopulation(BoardBlockEntity.java:138)
	at io.ejekta.bountiful.content.board.BoardBlockEntity$Companion.tick(BoardBlockEntity.java:277)
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.tick(BoardBlock.java:44)
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.tick(BoardBlock.java:44)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2960.method_45135(class_2960.java:232)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.minecraft.class_2960.<init>(class_2960.java:56)
	at io.ejekta.bountiful.bounty.types.builtin.BountyTypeItem.isValid(BountyTypeItem.java:27)
	at io.ejekta.bountiful.data.PoolEntry.isValid(PoolEntry.java:44)
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor$lambda$5(BountyCreator.java:207)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
	at io.ejekta.bountiful.content.BountyCreator$Companion.getRewardsFor(BountyCreator.java:212)
	at io.ejekta.bountiful.content.BountyCreator$Companion.access$getRewardsFor(BountyCreator.java:186)
	at io.ejekta.bountiful.content.BountyCreator.genRewardEntries(BountyCreator.java:81)
	at io.ejekta.bountiful.content.BountyCreator.create(BountyCreator.java:43)
	at io.ejekta.bountiful.content.BountyCreator.stack_delegate$lambda$1(BountyCreator.java:32)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ejekta.bountiful.content.BountyCreator.getStack(BountyCreator.java:31)
	at io.ejekta.bountiful.content.BountyCreator$Companion.createBountyItem(BountyCreator.java:194)
	at io.ejekta.bountiful.content.board.BoardBlockEntity.randomlyUpdateBoard(BoardBlockEntity.java:157)
	at io.ejekta.bountiful.content.board.BoardBlockEntity.tryInitialPopulation(BoardBlockEntity.java:138)
	at io.ejekta.bountiful.content.board.BoardBlockEntity$Companion.tick(BoardBlockEntity.java:277)
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.tick(BoardBlock.java:44)
	at io.ejekta.bountiful.content.board.BoardBlock$getTicker$1.tick(BoardBlock.java:44)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: bountiful:board-be // io.ejekta.bountiful.content.board.BoardBlockEntity
	Block: Block{bountiful:bountyboard}
	Block location: World: (5160,72,-2384), Section: (at 8,8,0 in 322,4,-149; chunk contains blocks 5152,-64,-2384 to 5167,319,-2369), Region: (10,-5; contains chunks 320,-160 to 351,-129, blocks 5120,-64,-2560 to 5631,319,-2049)
	Block: Block{bountiful:bountyboard}
	Block location: World: (5160,72,-2384), Section: (at 8,8,0 in 322,4,-149; chunk contains blocks 5152,-64,-2384 to 5167,319,-2369), Region: (10,-5; contains chunks 320,-160 to 351,-129, blocks 5120,-64,-2560 to 5631,319,-2049)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['TheynT'/69, l='ServerLevel[seed_test_more_mods]', x=4970.77, y=94.00, z=-2626.35]]
	Chunk stats: 5852
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,165,0), Section: (at 0,5,0 in 0,10,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 36185 game time, 1500 day time
	Level name: seed_test_more_mods
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 83887 (now: false), thunder time: 91169 (now: false)
	Known server brands: quilt
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ejektaflex** [comment] 2023-06-29 16:22
This is a duplicate of #234

**Closed as completed by ejektaflex** 2023-06-29 16:22 UTC
Labels: bug
