### ISSUE TITLE
[Bug]: When grabbing a bounty on a server causing ticking player

### ISSUE THREAD

**Issue by YukiRainee** [ejektaflex/Bountiful#260] opened 2023-12-12 08:24 UTC
### What happened?

To be able to grab the bounty and hold on to it to turn it on

### How can we reproduce it?

1. Install the mod on a server
2. find a village with bounty board or place one down
3. grab any bounty and drag it directly into inventory and exit the board...
4. (scroll to bounty if needed)
5. you should get kicked from the server

### Mod Version

6.0.3+1.20.1

### Mod Loader

Forge

### Mod Loader Version

Neoforge 47.1.80

### Relevant log output

[08:20:01] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[08:20:01] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        Index: 6
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: ASM: class dev.xkmc.l2library.init.events.BaseCapabilityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: net.minecraftforge.eventbus.EventBus$$Lambda$1632/0x0000002801728f60@6f2e0f7b
                5: ASM: class electrodynamics.common.event.ServerEventHandler tick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: class net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class net.mcreator.createsweetsandtreets.procedures.HoldTheRainbowProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: me.desht.pneumaticcraft.common.event.PneumaticArmorHandler@4ef237c4 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class me.desht.pneumaticcraft.common.pneumatic_armor.CommonArmorHandler$Listeners onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: xaero.common.events.FMLCommonEventHandler@415ec932 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class com.aetherteam.aether.event.listeners.EntityListener onRiderTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onPlayerTraveling(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class com.teammetallurgy.aquaculture.item.neptunium.NeptuniumArmor onLivingTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: xaero.map.events.FMLCommonEvents@ad6dcd handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class com.hollingsworth.arsnouveau.common.potions.GravityEffect entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents playerOnTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class com.hollingsworth.arsnouveau.common.event.LightEvents onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: net.minecraftforge.eventbus.EventBus$$Lambda$1632/0x0000002801728f60@b28ea07
                21: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@228200c playerTickPost(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: class com.enderio.base.common.hangglider.PlayerMovementHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class com.elfmcys.yesstevemodel.o00o0O0ooO0Ooo0OOo0OO0OO OooOo0oOoOO0o00OO000oO00(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: mekanism.common.CommonPlayerTickHandler@20929438 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: de.maxhenkel.camera.ServerEvents@6b69c878 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: mcjty.lib.setup.ModSetup$EventHandler@3141a631 onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@7e400c46 onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                28: ASM: me.lucko.spark.forge.ForgeTickHook@5e6a1242 onTick(Lnet/minecraftforge/event/TickEvent;)V
                29: ASM: me.lucko.spark.forge.ForgeTickReporter@766079f7 onTick(Lnet/minecraftforge/event/TickEvent;)V
                30: LOWEST
                31: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler onGlideTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at TRANSFORMER/bountiful@6.0.3+1.20.1/io.ejekta.bountiful.content.BountyItem.m_7626_(BountyItem.java:35)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911)
        at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30)
        at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19)
        at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@47.1.81/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:927)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:285)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:840)

[08:20:01] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /172.115.190.95:27201
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:krypton.mixins.json:shared.player.ServerPlayerEntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_night_skip.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.source_dependent_iframes.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.can_breathe_water.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_conduit_power.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_dolphins_grace.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_hunger.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:krypton.mixins.json:shared.network.util.ServerPlayNetworkHandlerAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:ad_astra-common.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:candlelight-common.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.crawling.MixinServerPlayNetworkHandler,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinServerPlayNetworkHandler,pl:mixin:APP:fabrication.mixins.json:h_unsafe.disable_moved_too_quickly.MixinServerPlayNetworkHandler,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayNetworkHandler,pl:mixin:APP:fabrication.mixins.json:b_utility.ping_privacy.MixinServerPlayNetworkHandler,pl:mixin:APP:fabrication.mixins.json:b_utility.despawning_items_blink.MixinServerPlayNetworkHandler,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:AdvancedPacketErrorLogging,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ClientConnectionMixin,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:fabrication.mixins.json:_general.config.MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-47.1.47.jar%2351!/:47.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2358!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
        at io.ejekta.bountiful.content.BountyItem.m_7626_(BountyItem.java:35) ~[Bountiful-6.0.3+1.20.1-forge.jar%23434!/:?] {re:classloading}
        at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.item.ItemStackMixin,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:garnished.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.item.ItemStackMixin,pl:mixin:APP:recipeessentials.mixins.json:nbt.ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:garnished.mixins.json:ItemStackMixin,pl:mixin:APP:fabrication.mixins.json:f_balance.disable_prior_work_penalty.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:e_mechanics.swap_conflicting_enchants.MixinItemStack,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinItemStack,pl:mixin:A}
        at net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30) ~[Create%20Sweets%20And%20Treats%201.1.jar%23461!/:?] {re:classloading}
        at net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19) ~[Create%20Sweets%20And%20Treats%201.1.jar%23461!/:?] {re:classloading}
        at net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[Create%20Sweets%20And%20Treats%201.1.jar%23461!/:?] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2355!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:927) ~[forge-1.20.1-47.1.81-universal.jar%23690!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:fruitsdelight.mixins.json:PlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:usefulslime.mixins.json:ClimbingPlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.fire_aspect_is_flint_and_steel.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.crawling.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.trident_enchantments.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.exp_drop.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.repelling_void.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.food_always_edible.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.infinity_crossbows.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.hunger_is.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.fireproof.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_hunger.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.despawning_items_blink.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinPlayerEntity,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:krypton.mixins.json:shared.player.ServerPlayerEntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_night_skip.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.source_dependent_iframes.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.can_breathe_water.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_conduit_power.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.permanent_dolphins_grace.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_hunger.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
        ... 9 more
[08:20:02] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: YukiRainee lost connection: Internal server error
[08:20:02] [Server thread/INFO] [minecraft/MinecraftServer]: YukiRainee left the game

**Comment by ejektaflex** [comment] 2023-12-12 08:30
Closing as a duplicate of #257 - uninstall Sweets and Treats, it's causing your crash, not Bountiful.

Thanks!

**Closed as completed by ejektaflex** 2023-12-12 08:30 UTC
Labels: bug
