### ISSUE TITLE
[Bug]:zombie_pigmans do not exist in 1.16.5

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful#163] opened 2022-01-05 03:33 UTC
### What happened?

I see that in "data\bountiful\bounties\pools\bountiful\hunting_objs.json",the last entity is "minecraft:zombie_pigman",which is wrong in 1.16.5 and will show as "entity.generic.name" in game.

### How can we reproduce it?

Replace "minecraft:zombie_pigman" with "minecraft:zombified_piglin".

### Mod Version

Bountiful-1.16.4-3.3.1

### Forge Version

36.2.22

**Comment by ejektaflex** [comment] 2022-01-06 17:31
Duplicate of #136

**Closed as completed by ejektaflex** 2022-01-06 17:31 UTC
Labels: bug
