### ISSUE TITLE
[Bug]: Game kicks me back to title screen when left clicking on bounties on the side of the board

### ISSUE THREAD

**Issue by Jollahs** [ejektaflex/Bountiful#302] opened 2024-11-28 03:42 UTC
### What happened?

Each time I left clicked a bounty on the board, the game soft crashes and boots me to the title screen. Repeated up to 5 times in a row.

### How can we reproduce it?

Open the bounty board, and left click on any of the available quests. I clicked on the bottom most quest. 

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.3.7

### Relevant log output

[crash-2024-11-27_20.33.27-client.txt](https://github.com/user-attachments/files/17942418/crash-2024-11-27_20.33.27-client.txt)

**Comment by ejektaflex** [comment] 2024-11-28 05:50
Closing as a duplicate of #270 .

**Closed as completed by ejektaflex** 2024-11-28 05:50 UTC
Labels: bug
