### ISSUE TITLE
Some errors at start

### ISSUE THREAD

**Issue by H4Mm3r** [ejektaflex/Bountiful#76] opened 2020-04-13 12:34 UTC
## Bug Report

[13Apr2020 14:31:58.721] [Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]: Couldn't parse loot table bountiful:blocks/bountyboard
[13Apr2020 14:31:59.284] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement bountiful:main/bounty_complete_epic: Invalid criterion trigger: bountiful:bounty_complete_epic
[13Apr2020 14:31:59.370] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement bountiful:main/bounty_complete_rare: Invalid criterion trigger: bountiful:bounty_complete_rare
[13Apr2020 14:31:59.430] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement bountiful:main/bounty_complete_common: Invalid criterion trigger: bountiful:bounty_complete_common
[13Apr2020 14:31:59.466] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement bountiful:main/bounty_complete_uncommon: Invalid criterion trigger: bountiful:bounty_complete_uncommon
[13Apr2020 14:31:59.466] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager/]: Parsing error loading custom advancement bountiful:main/royal_mandate: Invalid criterion trigger: bountiful:royal_mandate

What should have happened:

**Minimal setup needed to reproduce**

- Forge version:  28.2.3
- Bountiful version: 3.1.0
- Other mods: a lot

**Comment by ejektaflex** [comment] 2020-04-14 10:38
These will be fixed in the next version, but gameplay for that version is working as intended (these errors are simply due to future features that haven't been fully implemented, but they are harmless). Closing for now, as a duplicate of #73 :^)

**Closed as completed by ejektaflex** 2020-04-14 10:38 UTC

**Comment by H4Mm3r** [comment] 2020-04-15 17:58
Thanks for the answer
