### ISSUE TITLE
[1.12.2] crash when opening bountyboard

### ISSUE THREAD

**Issue by xemnes** [ejektaflex/Bountiful#103] opened 2020-08-31 05:09 UTC
## Bug Report

**Observed Behaviour**

What happened: when opening the bountyboard, i immediately crash.

Crash log: https://pastebin.com/wXfZsXtu

**Expected Behaviour**

What should have happened: the bountryboard should open and view bounties.

**Minimal setup needed to reproduce**

- Forge version: 2584
- Bountiful version: 2.2.2
- Other mods: mods are listed in the crash log

**Steps to reproduce**

How to recreate this: open the bounty board

**Comment by ejektaflex** [comment] 2020-08-31 17:38
Uhhh what's your inventory like? Do you have any mods that affect your inventory size?

You didn't share the full log, and there's no mention of any Bountiful code being ran in what you sent me (besides that it is loaded), so I'm at a bit of a loss. :^)

**Comment by xemnes** [comment] 2020-08-31 21:19
no, just regular sized inventory. there is a hotbar swap feature in quark that is close to that maybe? baubles and aether modify equipment slots, theres also backpacks but i wasnt wearing one when i opened it. quark adds an inventory search bar and buttons for sorting and moving.

forgot to mention it also crashes the server when opened on the server, i managed to open one of them fine as it had only one bounty, no crash, but it seems if theres a lot of bounties in them, it crashes

**Comment by ejektaflex** [comment] 2020-09-04 16:14
It would be nice to see that crash log on the serverside! Otherwise, have you messed with the config files at all? I'm really not sure what would be causing a crash there. Honestly, it's not even calling any Bountiful code so it could be another mod. I'd have to see the server log when it crashes to know for certain.

**Comment by xemnes** [comment] 2020-09-04 17:08
sure, here you go: https://pastebin.com/T03k3DUq
config files have not been touched.

**Comment by ejektaflex** [comment] 2020-09-06 07:04
Right, so as far as I'm aware: nothing about this log is indicating that it is due to Bountiful at all, even if it's happening when opening a bounty board. The game is fundamentally wrong about the slot count of the GUI that it is receiving from the network when it synchronizes the container, something that should never be happening with Forge.

.. And it doesn't happen in  *plain* Forge! I've never seen this problem before. However, you're not using Forge regularly like everyone else, you're using **Mohist**. And unfortunately, since the stack trace doesn't point to any particular mod but intead the Forge ItemStackHandler (as dictated by what code Mohist is currently using), I've got to assume that Mohist has some sort of bug here with their Forge implementation. 

That being said, it could be something else (something running ASM code? A coremod?), but all indicators lead to an inconsistency between what Forge *should* be doing and what it is *currently* doing, probably due to Mohist having to modify the Forge codebase for compatibility with other server implementations.

This means that the fix is unfortunately out of my control. You'll have to file a bug report with them if you want to see any progress made on this.

**Comment by xemnes** [comment] 2020-09-06 13:17
It can’t be just mohist as I initially started this report as a client side issue as I am also crashing client side any my client does not have mohist installed. ive tested this is in a single player world first before even testing it on the server.

ive even removed all my mods and it still crashes. if this cant be fixed then i guess i will have to just remove the mod.

**Comment by ejektaflex** [comment] 2020-09-06 18:06
Well, then if it's not Mohist, it's going to be a coremod or access transformer. You have tons of coremods in your load order:
```
DynamicSurroundings
ImmersiveEngineering
engineers_doots
OpenComputers
Forgelin (I guess you need this for Bountiful though)
Quark
iceandfire
CTM
astralsorcery
NotEnoughIDs
llibrary
BetterFoliage
EnderCore
VanillaFix
TheBetweenlands
FoamFix
ResourceLoader
SmoothWater
```

Any of these mods could also be transforming regular behavior. You should try remove them systemically until you figure out which one is causing Bountiful to work incorrectly.

Otherwise, I'm going to mark this as can-not-reproduce, because I can't seem to reproduce your issue without any other mods installed, like you are suggesting ¯\\_(ツ)_/¯ If I could, it would have been caught during testing, since I obviously test this mod quite a bit before releasing it.

If you could provide a log showing the crash in a modded single player environment with no other mods loaded (besides Shadowfact's Forgelin, of course), that may help.

**Comment by ejektaflex** [comment] 2020-09-10 23:27
@xemnes If you could provide the above, that would really help me fix this. :^)

**Comment by xemnes** [comment] 2020-09-11 04:37
sorry, i never got round to the debugging as i have been rather busy, i will at some point go through each of those mods and see if any of them cause the crash over the weekend

**Comment by ejektaflex** [comment] 2020-09-11 08:09
Sounds good. Try test w/o any other mods (besides Forgelin) first, just to be sure. If it's doing it on it's own, that changes a lot!

**Comment by xemnes** [comment] 2020-09-12 18:11
hmmm, i cant get it to crash with any of those mods added. i do have a hunch though, perhaps its because i go over the id limit maybe? which is why i have notenoughids installed.

**Comment by ejektaflex** [comment] 2020-09-12 21:37
That could possibly be it :^) there's definitely some code wizardry used in that mod so I wouldn't be surprised. 

I'm going to bet that it's not Bountiful but instead some other mod interacting with Bountiful, since nothing indicated that it was due to any Bountiful code. I'm going to close this issue since it doesn't seem to be a problem on our end, but if you are reasonably sure about what mod it is conflicting with, you can respond here and I'll try reproduce it, then file a bug report on their repo.

**Closed as completed by ejektaflex** 2020-09-12 21:37 UTC
