### ISSUE TITLE
[Bug] [1.20.1]: Invalid character in resource location

### ISSUE THREAD

**Issue by hron84** [ejektaflex/Bountiful#238] opened 2023-07-04 20:12 UTC
### What happened?

I tried to shift+right click with a decree to a bounty table.

(Sadly, it messes up the save file, I cannot load the save from now)

### How can we reproduce it?

Errmm... earn some decree and shift right click? Honeslty, I just learning the mod, I dunno the exact circumstances. Please ask me questions if you need anyting!

### Mod Version

6.0.1

### Mod Loader

Forge

### Mod Loader Version

47.0.35

### Relevant log output

[crash-2023-07-04_22.07.56-server.txt](https://github.com/ejektaflex/Bountiful/files/11952126/crash-2023-07-04_22.07.56-server.txt)

**Comment by ejektaflex** [comment] 2023-07-04 21:09
Closing as a duplicate of #234. I'll get around to it very soon, as I am now back from vacation :)

**Closed as completed by ejektaflex** 2023-07-04 21:09 UTC
Labels: bug

**Comment by hron84** [comment] 2023-07-04 23:48
Thanks
