### ISSUE TITLE
[Suggestion]: Support the most downloadable mods version

### ISSUE THREAD

**Issue by vgrynch** [ejektaflex/Bountiful#247] opened 2023-08-31 08:39 UTC
### What happened?

1.19.2 is the most downloadable and supported version of mods for almost all mod authors. Would be good if this mod supports it too.

Thanks!

### Mod Version

6.0.0

### Mod Loader

Forge

### Mod Loader Version

43.2.21

**Comment by ejektaflex** [comment] 2023-09-08 17:52
I don't have time to support 1.19.2. Anyone can submit their port of it via a PR, but as it stands, I have too many other things going on, and so I only have enough time to keep the mod up to date with the latest versions of Minecraft. Sorry about that!

Closing this, as it's not a bug report.

**Closed as completed by ejektaflex** 2023-09-08 17:52 UTC
Labels: bug, wontfix
