### ISSUE TITLE
Loot Table Issues

### ISSUE THREAD

**Issue by ModernGamingWorld** [ejektaflex/Bountiful#126] opened 2021-04-09 16:19 UTC
## Bug Report

**Observed Behaviour**

What happened:
Server console gets spammed by this 

Crash log: 
https://gist.github.com/ModernGamingWorld/5144f2ea9cdca513d4e9750e369c9b90

**Expected Behaviour**
Something to be fixed

What should have happened:

**Minimal setup needed to reproduce**

- Forge version: 36.1.4
- Bountiful version: 1.16.4-3.3.1
- Other mods:

**Steps to reproduce**

How to recreate this:

**Comment by ejektaflex** [comment] 2021-04-09 20:30
Closed as a duplicate of #99  / #122

**Closed as completed by ejektaflex** 2021-04-09 20:30 UTC
